'use strict';
console.log("CNN");

    var title=document.getElementsByClassName("pg-headline")[0];
    var footer = document.getElementsByClassName("zn-body__paragraph zn-body__footer")[0];
    var content = document.getElementsByClassName("zn-body-text")[0];
    console.log(footer);
    

    var request = new XMLHttpRequest();

    request.open('POST', 'https://rebiasednews.ddns.net', true);
    request.onreadystatechange = function() {
        if (this.readyState != 4) {
            var el = document.getElementById('change');

            var newEl = document.createElement('div');
            newEl.classList.add("loader");
            var att = document.createAttribute("id");
            att.value = "change";
            newEl.setAttributeNode(att);

            // replace el with newEL
            el.parentNode.replaceChild(newEl, el);
        }
    }
    request.onerror = function() {
        window.alert("Sorry, this article is not ready yet, try again in a few minutes");
    }
    request.onload = function() {
        if(this.response === undefined || this.response.length == 0) {
            // TODO: nothing found
            console.log(this.response);
            console.log("Nothing found");
        } else {
            var resp = this.response;
            console.log(resp);
            content.innerHTML = '<p>' + resp +'</p>'+ '<p class="zn-body__paragraph zn-body__footer"> This article was generated by a ROBOT</p>';
            var el = document.getElementById('change');

            var newEl = document.createElement('button');
            newEl.classList.add("btn");
            newEl.innerHTML = "ReBiase this article!";
            var att = document.createAttribute("id");
            att.value = "change";
            newEl.setAttributeNode(att);

            // replace el with newEL
            el.parentNode.replaceChild(newEl, el);
        }
    };
    request.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    var data = JSON.stringify({"title": title.textContent, "body": ""});
    request.send(data);
